services:
  app:
    image: cpan0/cs_badui:latest
    pull_policy: always
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
